### Get Data

In [103]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import TruncatedSVD

restaurants_df = pd.read_csv('data/restaurants.csv')
restaurants_df.drop(columns=['Unnamed: 0'], inplace=True)
restaurants_df.head()

,_id,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,5e726975fc4274bf7ac0b21d,f-m7-hyFzkf0HSEeQ2s-9A,fog-harbor-fish-house-san-francisco-2,Fog Harbor Fish House,https://s3-media1.fl.yelpcdn.com/bphoto/Lv7tIR...,False,https://www.yelp.com/biz/fog-harbor-fish-house...,6050,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.0,"{'latitude': 37.809041, 'longitude': -122.410233}",['restaurant_reservation'],$$,"{'address1': 'Pier 39', 'address2': 'Ste A-202...",1.415421e+10,(415) 421-2442,5827.740044
1,5e726975fc4274bf7ac0b21e,ZoZjbOYR-apY8XvommlNUA,the-house-san-francisco,The House,https://s3-media2.fl.yelpcdn.com/bphoto/UzrNIk...,False,https://www.yelp.com/biz/the-house-san-francis...,4838,"[{'alias': 'asianfusion', 'title': 'Asian Fusi...",4.5,"{'latitude': 37.79851, 'longitude': -122.40706}",['restaurant_reservation'],$$$,"{'address1': '1230 Grant Ave', 'address2': '',...",1.415987e+10,(415) 986-8612,4911.928932
2,5e726975fc4274bf7ac0b21f,z4g4bZPR-Z8bFlwv9APl2w,presidio-kebab-san-francisco,Presidio Kebab,https://s3-media2.fl.yelpcdn.com/bphoto/7ZiQyS...,False,https://www.yelp.com/biz/presidio-kebab-san-fr...,11,"[{'alias': 'kebab', 'title': 'Kebab'}]",4.5,"{'latitude': 37.7880728, 'longitude': -122.446...",[],$$,"{'address1': '3277 Sacramento St', 'address2':...",1.415948e+10,(415) 947-7163,3155.764988
3,5e726975fc4274bf7ac0b220,XQLmEdXoMzOpffwoFaBtaQ,kitchen-story-san-francisco,Kitchen Story,https://s3-media1.fl.yelpcdn.com/bphoto/RbFDSB...,False,https://www.yelp.com/biz/kitchen-story-san-fra...,3337,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.0,"{'latitude': 37.7642352, 'longitude': -122.430...","['restaurant_reservation', 'pickup']",$$,"{'address1': '3499 16th St', 'address2': '', '...",1.415525e+10,(415) 525-4905,625.156644
4,5e726975fc4274bf7ac0b221,gqVl3RprESEqkIPeJH0yOg,zazie-san-francisco,Zazie,https://s3-media3.fl.yelpcdn.com/bphoto/uuRvEU...,False,https://www.yelp.com/biz/zazie-san-francisco?a...,4388,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.0,"{'latitude': 37.765244, 'longitude': -122.4501...","['delivery', 'restaurant_reservation']",$$,"{'address1': '941 Cole St', 'address2': '', 'a...",1.415565e+10,(415) 564-5332,1294.862434

In [102]:
restaurants_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _id            1000 non-null   object
 1   id             1000 non-null   object
 2   alias          1000 non-null   object
 3   name           1000 non-null   object
 4   image_url      1000 non-null   object
 5   is_closed      1000 non-null   bool
 6   url            1000 non-null   object
 7   review_count   1000 non-null   int64
 8   categories     1000 non-null   object
 9   rating         1000 non-null   float64
 10  coordinates    1000 non-null   object
 11  transactions   1000 non-null   object
 12  price          934 non-null    object
 13  location       1000 non-null   object
 14  phone          964 non-null    float64
 15  display_phone  964 non-null    object
 16  distance       1000 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(12)
memory usage: 126.1+ KB

In [2]:
user_reviews_df = pd.read_csv('data/user_reviews.csv')
user_reviews_df.drop(columns=['Unnamed: 0'], inplace=True)
user_reviews_df

,_id,id,url,text,rating,time_created,user
0,5e727e98fc4274bf7ac0b605,WnID6ZjQfcjdYr13TV24xQ,https://www.yelp.com/biz/fog-harbor-fish-house...,Omg if I could give this place more stars I WO...,5,2020-03-13 19:41:09,"{'id': 'eahdnZ1D2YD9OqkHU53Iow', 'profile_url'..."
1,5e727e98fc4274bf7ac0b606,sdcO_t0un1J7Wb2ohQ3qqg,https://www.yelp.com/biz/fog-harbor-fish-house...,Fog harbor was pretty good. We shared half a c...,4,2020-03-09 16:42:33,"{'id': 'DQhlYtmUQATLAleuKQosKw', 'profile_url'..."
2,5e727e98fc4274bf7ac0b607,u4aDtp9BYQk4hL4Ty9VI3w,https://www.yelp.com/biz/fog-harbor-fish-house...,I'm so happy this place lived up to the hype! ...,5,2020-03-09 13:04:43,"{'id': '1v2uYP_KhrA1a1BFsON-aQ', 'profile_url'..."
3,5e727e98fc4274bf7ac0b608,7s7GqVzDaml3n-tWIdvZSg,https://www.yelp.com/biz/the-house-san-francis...,I had high expectations about this place becau...,5,2020-03-04 20:40:32,"{'id': '7tcjiB6EryTpieKgsSxz2Q', 'profile_url'..."
4,5e727e98fc4274bf7ac0b609,0HnIMYxyQN3qo-oZXyGFdg,https://www.yelp.com/biz/the-house-san-francis...,"In our most recent trip to San Francisco, as t...",4,2020-03-14 08:51:00,"{'id': 'M0OfxGsd--mNhKFxiyla8w', 'profile_url'..."
...,...,...,...,...,...,...,...
2991,5e727e99fc4274bf7ac0c1b4,b0peUmN6E-5wr6mWNykLIA,https://www.yelp.com/biz/noren-izakaya-san-fra...,Out of 5 stars\nEntrance & Welcome: 5\nFood Qu...,5,2020-03-08 21:04:04,"{'id': '6BABpco5nmw20vPehLSF3g', 'profile_url'..."
2992,5e727e99fc4274bf7ac0c1b5,LlWYWIY_2aLMa9K8-UiQwg,https://www.yelp.com/biz/noren-izakaya-san-fra...,Noren is a rare walk into a Tokyo bar right he...,5,2020-02-06 08:57:21,"{'id': '9djchRbqRnmyhq4X808k-w', 'profile_url'..."
2993,5e727e99fc4274bf7ac0c1b6,rPXwV8n2vFYclz_nox3gZQ,https://www.yelp.com/biz/sini-san-francisco-3?...,Catered lunch for 19 from Sini last Monday (11...,5,2019-11-23 15:23:18,"{'id': 'u92jV0zgxyYBIcJdDbL7aA', 'profile_url'..."
2994,5e727e99fc4274bf7ac0c1b7,KU-A_BFMwR_HAHH-7gEsHw,https://www.yelp.com/biz/sini-san-francisco-3?...,"Food is alright, but UberEats functionality is...",1,2020-03-10 16:48:52,"{'id': 'ID1hO_IiIDS8UEYtHizlMw', 'profile_url'..."
2995,5e727e99fc4274bf7ac0c1b8,FswssiLPaQUS0BjcWXFvuA,https://www.yelp.com/biz/sini-san-francisco-3?...,"The freshly baked, straight-out-of-the-oven pi...",4,2020-01-27 22:21:25,"{'id': 'hgaChGBAZXo2dOWdvJfLDw', 'profile_url'..."

In [5]:
import ast
user_reviews_df['user_id'] = user_reviews_df['user'].apply(lambda x: ast.literal_eval(x)['id'])
user_reviews_df['slug'] = user_reviews_df['url'].apply(lambda x: x.split("/biz/")[1].split("?")[0])
user_reviews_df

,_id,id,url,text,rating,time_created,user,user_id,slug
0,5e727e98fc4274bf7ac0b605,WnID6ZjQfcjdYr13TV24xQ,https://www.yelp.com/biz/fog-harbor-fish-house...,Omg if I could give this place more stars I WO...,5,2020-03-13 19:41:09,"{'id': 'eahdnZ1D2YD9OqkHU53Iow', 'profile_url'...",eahdnZ1D2YD9OqkHU53Iow,fog-harbor-fish-house-san-francisco-2
1,5e727e98fc4274bf7ac0b606,sdcO_t0un1J7Wb2ohQ3qqg,https://www.yelp.com/biz/fog-harbor-fish-house...,Fog harbor was pretty good. We shared half a c...,4,2020-03-09 16:42:33,"{'id': 'DQhlYtmUQATLAleuKQosKw', 'profile_url'...",DQhlYtmUQATLAleuKQosKw,fog-harbor-fish-house-san-francisco-2
2,5e727e98fc4274bf7ac0b607,u4aDtp9BYQk4hL4Ty9VI3w,https://www.yelp.com/biz/fog-harbor-fish-house...,I'm so happy this place lived up to the hype! ...,5,2020-03-09 13:04:43,"{'id': '1v2uYP_KhrA1a1BFsON-aQ', 'profile_url'...",1v2uYP_KhrA1a1BFsON-aQ,fog-harbor-fish-house-san-francisco-2
3,5e727e98fc4274bf7ac0b608,7s7GqVzDaml3n-tWIdvZSg,https://www.yelp.com/biz/the-house-san-francis...,I had high expectations about this place becau...,5,2020-03-04 20:40:32,"{'id': '7tcjiB6EryTpieKgsSxz2Q', 'profile_url'...",7tcjiB6EryTpieKgsSxz2Q,the-house-san-francisco
4,5e727e98fc4274bf7ac0b609,0HnIMYxyQN3qo-oZXyGFdg,https://www.yelp.com/biz/the-house-san-francis...,"In our most recent trip to San Francisco, as t...",4,2020-03-14 08:51:00,"{'id': 'M0OfxGsd--mNhKFxiyla8w', 'profile_url'...",M0OfxGsd--mNhKFxiyla8w,the-house-san-francisco
...,...,...,...,...,...,...,...,...,...
2991,5e727e99fc4274bf7ac0c1b4,b0peUmN6E-5wr6mWNykLIA,https://www.yelp.com/biz/noren-izakaya-san-fra...,Out of 5 stars\nEntrance & Welcome: 5\nFood Qu...,5,2020-03-08 21:04:04,"{'id': '6BABpco5nmw20vPehLSF3g', 'profile_url'...",6BABpco5nmw20vPehLSF3g,noren-izakaya-san-francisco
2992,5e727e99fc4274bf7ac0c1b5,LlWYWIY_2aLMa9K8-UiQwg,https://www.yelp.com/biz/noren-izakaya-san-fra...,Noren is a rare walk into a Tokyo bar right he...,5,2020-02-06 08:57:21,"{'id': '9djchRbqRnmyhq4X808k-w', 'profile_url'...",9djchRbqRnmyhq4X808k-w,noren-izakaya-san-francisco
2993,5e727e99fc4274bf7ac0c1b6,rPXwV8n2vFYclz_nox3gZQ,https://www.yelp.com/biz/sini-san-francisco-3?...,Catered lunch for 19 from Sini last Monday (11...,5,2019-11-23 15:23:18,"{'id': 'u92jV0zgxyYBIcJdDbL7aA', 'profile_url'...",u92jV0zgxyYBIcJdDbL7aA,sini-san-francisco-3
2994,5e727e99fc4274bf7ac0c1b7,KU-A_BFMwR_HAHH-7gEsHw,https://www.yelp.com/biz/sini-san-francisco-3?...,"Food is alright, but UberEats functionality is...",1,2020-03-10 16:48:52,"{'id': 'ID1hO_IiIDS8UEYtHizlMw', 'profile_url'...",ID1hO_IiIDS8UEYtHizlMw,sini-san-francisco-3
2995,5e727e99fc4274bf7ac0c1b8,FswssiLPaQUS0BjcWXFvuA,https://www.yelp.com/biz/sini-san-francisco-3?...,"The freshly baked, straight-out-of-the-oven pi...",4,2020-01-27 22:21:25,"{'id': 'hgaChGBAZXo2dOWdvJfLDw', 'profile_url'...",hgaChGBAZXo2dOWdvJfLDw,sini-san-francisco-3

In [49]:
restaurants_name_df = restaurants_df[['alias', 'name']]
restaurants_name_df

                                     alias                   name
0    fog-harbor-fish-house-san-francisco-2  Fog Harbor Fish House
1                  the-house-san-francisco              The House
2             presidio-kebab-san-francisco         Presidio Kebab
3              kitchen-story-san-francisco          Kitchen Story
4                      zazie-san-francisco                  Zazie
..                                     ...                    ...
995       halal-wings-plus-san-francisco-2       Halal Wings Plus
996               say-cheese-san-francisco             Say Cheese
997                  asiento-san-francisco                Asiento
998            noren-izakaya-san-francisco          Noren Izakaya
999                   sini-san-francisco-3                   SINI

[1000 rows x 2 columns]

In [50]:
reviews_df = user_reviews_df[['user_id', 'slug', 'rating']]
reviews_df

                     user_id                                   slug  rating
0     eahdnZ1D2YD9OqkHU53Iow  fog-harbor-fish-house-san-francisco-2       5
1     DQhlYtmUQATLAleuKQosKw  fog-harbor-fish-house-san-francisco-2       4
2     1v2uYP_KhrA1a1BFsON-aQ  fog-harbor-fish-house-san-francisco-2       5
3     7tcjiB6EryTpieKgsSxz2Q                the-house-san-francisco       5
4     M0OfxGsd--mNhKFxiyla8w                the-house-san-francisco       4
...                      ...                                    ...     ...
2991  6BABpco5nmw20vPehLSF3g            noren-izakaya-san-francisco       5
2992  9djchRbqRnmyhq4X808k-w            noren-izakaya-san-francisco       5
2993  u92jV0zgxyYBIcJdDbL7aA                   sini-san-francisco-3       5
2994  ID1hO_IiIDS8UEYtHizlMw                   sini-san-francisco-3       1
2995  hgaChGBAZXo2dOWdvJfLDw                   sini-san-francisco-3       4

[2996 rows x 3 columns]

In [52]:
ratings_df = reviews_df.merge(restaurants_name_df, left_on='slug', right_on='alias')
ratings_df.drop(columns=['slug', 'alias'], inplace=True)
ratings_df

                     user_id  rating                   name
0     eahdnZ1D2YD9OqkHU53Iow       5  Fog Harbor Fish House
1     DQhlYtmUQATLAleuKQosKw       4  Fog Harbor Fish House
2     1v2uYP_KhrA1a1BFsON-aQ       5  Fog Harbor Fish House
3     7tcjiB6EryTpieKgsSxz2Q       5              The House
4     M0OfxGsd--mNhKFxiyla8w       4              The House
...                      ...     ...                    ...
2922  6BABpco5nmw20vPehLSF3g       5          Noren Izakaya
2923  9djchRbqRnmyhq4X808k-w       5          Noren Izakaya
2924  u92jV0zgxyYBIcJdDbL7aA       5                   SINI
2925  ID1hO_IiIDS8UEYtHizlMw       1                   SINI
2926  hgaChGBAZXo2dOWdvJfLDw       4                   SINI

[2927 rows x 3 columns]

### Building a Utility Matrix

In [77]:
def utility_matrix():
    ratings_crosstab = ratings_df.pivot_table(values='rating', index='user_id', columns='name', fill_value=0)
    return ratings_crosstab

### Transposing the Matrix

In [54]:
ratings_crosstab.shape

(2194, 940)

In [80]:
def transpose_matrix(ratings_crosstab):
    return ratings_crosstab.values.T

### Decomposing the Matrix

In [81]:
def svd_fit_transform(X):
    SVD = TruncatedSVD(n_components=12, random_state=17)
    resultant_matrix = SVD.fit_transform(X)
    return resultant_matrix

### Generating a Correlation Matrix

In [89]:
def corr_matrix(resultant_matrix):
    corr_mat = np.corrcoef(resultant_matrix)
    return corr_mat

### Isolate Benu from Correlation Matrix

In [90]:
restaurant_names = ratings_crosstab.columns
restaurant_list = list(restaurant_names)

benu = restaurant_list.index('Benu')
print(restaurant_names)

Index(['1428 HAIGHT Patio Cafe & Crepery', '1601 Bar & Kitchen', '1608 Bistro',
       '1760', '20 Spot', '25 Lusk', '3rd Cousin',
       '4505 Burgers & BBQ - San Francisco', '54 Mint - Ristorante Italiano',
       '5A5 Steak Lounge',
       ...
       'Zazie', 'Zen Yai Thai Restaurant', 'Zero Zero', 'a Mano',
       'b&b - Banh Mi & Boba', 'barvale', 'opa cafe', 'pomelo on Judah',
       'reception', 'um.ma'],
      dtype='object', name='name', length=940)

In [91]:
def get_index_of_restaurant(corr_mat, restaurant_input):
    restaurant_names = ratings_crosstab.columns
    restaurant_list = list(restaurant_names)

    restaurant = restaurant_list.index(restaurant_input)
    corr_rest = corr_mat[restaurant]
    return restaurant_names, corr_rest

### Recommending a Highly Correlated Restaurant

In [92]:
def return_highly_correlated_list(restaurant_names, corr_rest, lr_bound=0.90):
    return list(restaurant_names[(corr_rest < 1.0) & (corr_rest > lr_bound)])

In [105]:
restaurant_input = input("Enter a Restaurant: ")
ratings_crosstab = utility_matrix()
X = transpose_matrix(ratings_crosstab)
resultant_matrix = svd_fit_transform(X)
corr_mat = corr_matrix(resultant_matrix)
restaurant_names, corr_rest = get_index_of_restaurant(corr_mat, restaurant_input)
print(return_highly_correlated_list(restaurant_names, corr_rest, lr_bound=0.90))

Enter a Restaurant: Benu
['20 Spot', 'Anomaly', 'Aria Korean Street Food', 'Atelier Crenn', 'Bella Trattoria', 'Bini’s Kitchen', "Capo's by Tony Gemignani", 'Cotogna', 'Del Popolo', 'Freshroll Vietnamese Rolls & Bowls', 'Izakaya KOU', 'Liholiho Yacht Club', 'Lolinda', 'Marlowe', "Mister Jiu's", 'Salt House', 'Sweet Maple', 'Zazang Korean Noodles']